<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Авторизация и регистрация</title>
  <link rel="stylesheet" href="../../app/assets/css/reset.css">
  <link rel="stylesheet" href="../../app/assets/css/main.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>

  <!-- Форма регистрации -->
  <div class="d-flex container w-100 mt-5 justify-content-center" style="margin-bottom: 220px">
    <form action="" method="post" enctype="multipart/form-data">
      <label class="form-label mt-1">Логин</label>
      <input type="text" class="form-control" name="login" placeholder="Введите свой логин">
      <label class="form-label mt-1">Почта</label>
      <input type="email" class="form-control" name="email" placeholder="Введите адрес своей почты">
      <label class="form-label mt-1">Пароль</label>
      <input type="password" class="form-control" name="password" placeholder="Введите пароль">
      <label class="form-label mt-1">Подтверждение пароля</label>
      <input type="password" class="form-control" name="password_confirm" placeholder="Подтвердите пароль">
      <button class="btn btn-primary mt-1 w-100" type="submit">Зарегистрироваться</button>
      <p>
        У вас уже есть аккаунт? - <a href="./login">авторизируйтесь</a>!
      </p>
      <?php foreach ($payload as $row) {
        if (!empty($row['login'])) {
          echo 'ngf';
      ?>
          <h2>Такой логин уже существует</h2>
      <?php
        } else {
          //header('location:/login');
          echo 'ghjk';
        }
        //echo 'sfdhhg';
      }
      //echo '<tr><td>' . $row['login'] . '</td><td>';

      //var_dump($payload);
      ?>
    </form>

  </div>


</body>

</html>